### ISSUE TITLE
Translated date can't be interpreted

### ISSUE THREAD

**Issue by fridde** [designwall/dw-question-answer#149]
Somehow this plugin seems to send the already translated date to the theme-builder, which, of course, causes an error. "47 sekunder sedan" (the swedish version of "47 seconds ago") can't be interpreted by PHP.

Any way to avoid this?
(This error appears when trying to show a single question that has already been posted)

```
Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (47 sekunder sedan) at position 0 (4): 
Unexpected character' in /storage/content/54/2000454/example.com/public_html/wp-content/themes/customizr/inc/parts/class-content-post_metas.php:203 Stack trace: 
#0 /storage/content/54/2000454/example.com/public_html/wp-content/themes/customizr/inc/parts/class-content-post_metas.php(203): DateTime->__construct('47 sekunder sed...')
 #1 /storage/content/54/2000454/example.com/public_html/wp-content/themes/customizr/inc/parts/class-content-post_metas.php(93): TC_post_metas->tc_has_update() 
#2 /storage/content/54/2000454/example.com/public_html/wp-content/themes/customizr/inc/parts/class-content-post_metas.php(68): TC_post_metas->tc_post_post_metas_view() 
#3 [internal function]: TC_post_metas->tc_post_metas('') #4 /storage/content/54/2000454/example.com/public_html/wp-includes/plugin.php(496): call_user_func_array(Array, Array) 
#5 /sto in /storage/content/54/2000454/example.com/public_html/wp-content/themes/customizr/inc/parts/class-content-post_metas.php on line 203
```

**Comment by fridde** [comment]
Well, somehow magically, the bug disappeared.

Strange, but fair enough...
