### ISSUE TITLE
conflict with wp_delete_attachment

### ISSUE THREAD

**Issue by fgrs** [designwall/dw-question-answer#236]
since I've been using this plugin I can't get wp_delete_attachment to work, page crashes with following error

`Fatal error: Uncaught Error: Call to undefined function is_user_logged_in() in /var/www/rafyouthstem.org.uk/htdocs/wp-content/plugins/dw-question-answer/inc/Permission.php:364 Stack trace: #0 /var/www/rafyouthstem.org.uk/htdocs/wp-includes/class-wp-hook.php(288): DWQA_Permission->restrict_single_question(Array) #1 /var/www/rafyouthstem.org.uk/htdocs/wp-includes/plugin.php(251): WP_Hook->apply_filters(Array, Array) #2 /var/www/rafyouthstem.org.uk/htdocs/wp-includes/class-wp-query.php(3151): apply_filters_ref_array('the_posts', Array) #3 /var/www/rafyouthstem.org.uk/htdocs/wp-includes/class-wp-query.php(3403): WP_Query->get_posts() #4 /var/www/rafyouthstem.org.uk/htdocs/wp-includes/nav-menu.php(972): WP_Query->query(Array) #5 /var/www/rafyouthstem.org.uk/htdocs/wp-includes/nav-menu.php(1011): wp_get_associated_nav_menu_items(1135, 'post_type') #6 /var/www/rafyouthstem.org.uk/htdocs/wp-includes/class-wp-hook.php(286): _wp_delete_post_menu_item(1135) #7 /var/www/rafyouthstem.org.uk/htdocs/wp-includes/class-wp-hook.php(310): W in /var/www/rafyouthstem.org.uk/htdocs/wp-content/plugins/dw-question-answer/inc/Permission.php on line 364`

any idea why?

**Comment by liuwanthang** [comment]
Please go to the https://designwall.com/question then create an new question, we will check and help yo, if you can not create the new question, you can let me know detail about the question here. We will check and update the plugin.
